// lang.js — переводы кошелька. Добавить язык = дописать блок. Логику не трогать.
window.I18N = {
  ru: {
    netError:'Ошибка сети при отправке', alias:'Алиас', aliasTitle:'Алиасы кошелька', yourAliases:'Ваши алиасы', noAliases:'Алиасов пока нет',
    newAlias:'Новый алиас', createAlias:'Создать алиас (0.001 WAVES)', aliasRules:'4–30 символов: a-z, 0-9, точка, дефис, @, _',
    aliasBad:'Недопустимое имя алиаса', aliasCreated:'Алиас создан! ID:', feeToken:'Токен для комиссии', 
    subtitle:'Децентрализованный кошелёк на блокчейне Waves', login:'Войти', create:'Создать новый кошелёк',
    seedLabel:'SEED-фраза', seedPlaceholder:'Введите вашу seed-фразу для входа, либо нажмите «Создать новый кошелёк».',
    enterSeedErr:'Введите seed-фразу или создайте новый кошелёк', seedShort:'Seed слишком короткий (мин. 12 символов)',
    newWallet:'Ваш новый кошелёк', writeDown:'Запишите эту фразу и храните в надёжном месте.', onlyKey:'Это единственный ключ к средствам.',
    yourSeed:'Ваша SEED-фраза', copy:'Скопировать', savedSeed:'Я записал(а) seed-фразу.', continue:'Продолжить →',
    myWallet:'Мой кошелёк', address:'Адрес', addr:'Адрес', refresh:'Обновить', logout:'Выйти', receive:'Получить',
    send:'Отправить', token:'Токен', recipient:'Получатель', amount:'Сумма', comment:'Комментарий (до 140 символов)',
    tokens:'Токены', history:'История', noOps:'Нет операций', received:'Получено', sent:'Отправлено',
    from:'От', to:'Кому', operation:'Операция', loadFail:'Не удалось загрузить',
    confirmSend:'Подтвердите отправку', fee:'Комиссия', cancel:'Отмена',
    badAddr:'Неверный адрес получателя (проверьте чексумму)', badAmount:'Неверная сумма', noFunds:'Недостаточно средств',
    notUnlocked:'Кошелёк не разблокирован', sentOk:'Отправлено! ID:', txSent:'Транзакция отправлена',
    seedCopied:'Seed скопирован', addrCopied:'Адрес скопирован', copyManual:'Скопируйте вручную', updated:'Обновлено',
    cryptoErr:'Ошибка крипто:', initCrypto:'Инициализация криптографии…',
    receiveTitle:'Получить средства', scanToSend:'Покажите этот QR для приёма', shareAddr:'Поделиться',
    addressBook:'Адресная книга', addContact:'Добавить', contactName:'Имя', save:'Сохранить', noContacts:'Пока пусто',
    pinTitle:'Установите PIN', pinEnter:'Введите PIN', pinCreate:'Придумайте PIN (4–8 цифр)', pinRepeat:'Повторите PIN',
    pinWrong:'Неверный PIN', pinMismatch:'PIN не совпадает', pinSet:'PIN установлен', unlock:'Разблокировать',
    pinShort:'PIN минимум 4 цифры', useSeed:'Войти по seed', forgetWallet:'Забыть сохранённый кошелёк',
    savePin:'Запомнить кошелёк (вход по PIN)', theme:'Тема', close:'Закрыть', selectContact:'Выбрать из книги',
    deleteAll:'Удалить',
    scanTitle:'Сканировать QR', scanHint:'Наведите камеру на QR-код адреса', 
    noCamera:'Камера недоступна (нужен HTTPS)', scanned:'Адрес распознан'
  },
  en: {
    netError:'Network error while sending', alias:'Alias', aliasTitle:'Wallet aliases', yourAliases:'Your aliases', noAliases:'No aliases yet',
    newAlias:'New alias', createAlias:'Create alias (0.001 WAVES)', aliasRules:'4–30 chars: a-z, 0-9, dot, dash, @, _',
    aliasBad:'Invalid alias name', aliasCreated:'Alias created! ID:', feeToken:'Fee token', 
    scanTitle:'Scan QR', scanHint:'Point the camera at an address QR code', noCamera:'Camera unavailable (HTTPS required)', 
    scanned:'Address recognized', subtitle:'Decentralized wallet on the Waves blockchain',
    login:'Login', create:'Create new wallet',
    seedLabel:'SEED phrase', seedPlaceholder:'Enter your seed phrase to log in, or click "Create new wallet".',
    enterSeedErr:'Enter a seed phrase or create a new wallet', seedShort:'Seed is too short (min 12 chars)',
    newWallet:'Your new wallet', writeDown:'Write down this phrase and keep it safe.', onlyKey:'It is the only key to your funds.',
    yourSeed:'Your SEED phrase', copy:'Copy', savedSeed:'I have written down the seed phrase.', continue:'Continue →',
    myWallet:'My wallet', address:'Address', addr:'Address', refresh:'Refresh', logout:'Logout', receive:'Receive',
    send:'Send', token:'Token', recipient:'Recipient', amount:'Amount', comment:'Comment (up to 140 chars)',
    tokens:'Tokens', history:'History', noOps:'No operations', received:'Received', sent:'Sent',
    from:'From', to:'To', operation:'Operation', loadFail:'Failed to load',
    confirmSend:'Confirm sending', fee:'Fee', cancel:'Cancel',
    badAddr:'Invalid recipient address (check checksum)', badAmount:'Invalid amount', noFunds:'Insufficient funds',
    notUnlocked:'Wallet is locked', sentOk:'Sent! ID:', txSent:'Transaction sent',
    seedCopied:'Seed copied', addrCopied:'Address copied', copyManual:'Copy manually', updated:'Updated',
    cryptoErr:'Crypto error:', initCrypto:'Initializing cryptography…',
    receiveTitle:'Receive funds', scanToSend:'Show this QR to receive', shareAddr:'Share',
    addressBook:'Address book', addContact:'Add', contactName:'Name', save:'Save', noContacts:'Empty',
    pinTitle:'Set a PIN', pinEnter:'Enter PIN', pinCreate:'Create a PIN (4–8 digits)', pinRepeat:'Repeat PIN',
    pinWrong:'Wrong PIN', pinMismatch:'PIN mismatch', pinSet:'PIN set', unlock:'Unlock',
    pinShort:'PIN min 4 digits', useSeed:'Login with seed', forgetWallet:'Forget saved wallet',
    savePin:'Remember wallet (login with PIN)', theme:'Theme', close:'Close', selectContact:'Pick from book',
    deleteAll:'Delete'
  }
};